### ISSUE TITLE
Incompatible with Buffer#slice / Buffer#subarray

### ISSUE THREAD

**Issue by tex0l** [craftzdog/react-native-buffer#1]
Hi!
When doing the following:
```js
const buff = Buffer.alloc(100)
buff.fill("a")
const slicedBuff = buff.subarray(0, 10)
const b64edBuff = slicedBuff.toString('base64')
const unB64edBuff = Buffer.from(b64edBuff, 'base64')
console.log('unB64edBuff length', unB64edBuff.length) // we expect this to log '10', but it logs '100'
```

**Comment by craftzdog** [comment]
Thanks, fixed it

**Comment by craftzdog** [comment]
btw, you should use `slice` instead of `subarray`

**Comment by tex0l** [comment]
Thanks!
Buffer#slice was recently deprecated on Node.js because it has a different behaviour than UInt8Array#slice from which it inherits if I understand correctly.

See: https://nodejs.org/api/buffer.html#bufslicestart-end

**Comment by craftzdog** [comment]
Oh, I didn't know that. 
It internally calls `subarray` though: https://github.com/craftzdog/react-native-buffer/blob/master/index.js#L1115
Looks like https://github.com/feross/buffer is necessary to be updated, then.

**Comment by craftzdog** [comment]
https://github.com/craftzdog/react-native-buffer/commit/1adab65d393ba30829e35ca83d4304d1d1303749 should fix that
