### ISSUE TITLE
RangeError: Property storage exceeds 196607 properties with hermes enabled

### ISSUE THREAD

**Issue by kapil21** [craftzdog/react-native-buffer#3]
While converting image base64 to binary or vice versa , Buffer.from(data,"base64") throws an exception for the size above 196607.

**Comment by efstathiosntonas** [comment]
@kapil21 can you explain how you managed to fix this?

**Comment by kapil21** [comment]
I was having the console.log() line where i was printing the buffer.  So problem was with console.log and i just removed it and it worked.
